# Generated by Django 6.0.1 on 2026-02-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='note',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
